<a href="https://colab.research.google.com/github/kys0554/bigdata/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 실습문제1

### 문제 1 
2*2 integers 다차원 배열을 초기화 하지 않은 상태로 생성하세요

In [3]:
import numpy as np
x = np.empty((2,2))
x

array([[4.68546273e-310, 0.00000000e+000],
       [4.68644744e-310, 4.68644695e-310]])

### 문제 2
x=np.array( [ [1,2,3],[4,5,6] ], dtype=np.int32) 일때 x와 동일한 shape를 가지는 다차원 배열을 초기화 하지 않은 상태로 생성하세요

In [5]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.int32)
y = np.empty_like(x)
y

array([[1932108083,      22080,          0],
       [         0,         64,          0]], dtype=int32)

### 문제 3
크기가 3인 단위 행렬을 생성하세요

In [18]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 문제 4
모든 원소가 1로 채워진 3*2 실수형 다차원 배열을 생성하세요

In [10]:
x = np.ones((3,2), dtype=np.float32)
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

### 문제 5
x=np.arange(4, dtype=np.int64) 일때 x 와 동일한 shape를 가지고 모든 원소가 1인 다차원 배열을 생성하세요

In [11]:
x = np.arange(4, dtype=np.int64)
y = np.ones_like(x)
y

array([1, 1, 1, 1])

### 문제 6
모든 원소가 0으로 채워진 3*2 실수형 다차원 배열을 생성하세요

In [12]:
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### 문제 7
x = np.arange(4, dtype=np.int64) 일때 x와 동일한 shape 의 영행렬을 생성하세요

In [14]:
x = np.arange(4, dtype=np.int64)
y = np.zeros_like(x)
y

array([0, 0, 0, 0])

### 문제 8
모든 원소가 6으로 채워진 2*5 uint(부호가 없는 정수) 다차원 배열을 생성하세요

In [15]:
x = np.full((2,5), 6, dtype=np.uint8)
x

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint8)

### 문제 9
x=np.arange(4, dtype=np.int64) 일때 x와 동일한 shape이고 모든 원소가 6인 다차원 배열을 생성하세요

In [16]:
x = np.arange(4, dtype=np.int64)
y = np.full_like(x, 6)
y

array([6, 6, 6, 6])

### 문제 10
[1,2,3] 배열을 생성하세요

In [84]:
x = np.array([1,2,3])
x.tolist()

[1, 2, 3]

### 문제 11
x=[1.2] 일때 (python list 상태) x를 배열로 변환하세요

In [19]:
x = [1,2]
np.array(x)

array([1, 2])

### 문제 12
x=[1,2] 일 때 (python list 상태) 일때 x를 float 형 배열로 변환하세요

In [21]:
x=[1,2]
np.array(x, dtype=np.float32)

array([1., 2.], dtype=float32)

### 문제 13
2,4,6,8,10 …. 100 을 원소를 가지는 배열을 생성하세요

In [24]:
x = np.linspace(2, 100, 50)
x

array([  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
        24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,
        46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,
        68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,
        90.,  92.,  94.,  96.,  98., 100.])

### 문제 14
3.0에서 10.0 까지 50개의 원소가 균일하게 분포된 1차원 배열을 생성하세요

In [26]:
x = np.linspace(3, 10, 50)
x

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

# 실습문제 2

### 문제1 
X가 10 x 10 x 3 의 다차원 배열일때 x의 두번째 차원이 150인 2차원 배열이 되도록 reshape 하세요.

In [36]:
x = np.ones((10, 10, 3))
x.reshape(2,150).shape

(2, 150)

### 문제 2 
x가 [ [1,2,3], [4,5,6] ] 일때 [1,4,2,5,3,6] 으로 변환하세요

In [85]:
x = np.array([[1,2,3],[4,5,6]])
x.T.reshape(1,6)

array([[1, 4, 2, 5, 3, 6]])

### 문제 3 
X가  [ [1,2,3], [4,5,6] ] 일때 flatten한 후 5번째 원소를 가져오세요

In [86]:
x = np.array([[1,2,3],[4,5,6]])
x.flatten()[4]
# x.item(4)

5

### 문제 4 
X = [ [1,2,3], [4,5,6]] , y = [ [7,8,9],[10,11,12] ] x와 y를 연결해서 [ [1,2,3,7,8,9], [4,5,6,10,11,12] ] 를 만드세요

In [44]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
np.concatenate((x,y), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 문제 5
X = [ [1,2,3], [4,5,6]] , y = [ [7,8,9],[10,11,12] ] x와 y를 연결해서 [ [1,2,3], [4,5,6], [7,8,9], [10,11,12] ] 를 만드세요

In [45]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
np.concatenate((x,y), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### 문제 6
x 가 [0,1,2] 일때, [0,0,1,1,2,2] 를 생성하세요

In [83]:
x = np.array([[0,1,2]])
print(np.concatenate((x,x), axis=0).flatten())

print(x+np.array([[0],[0]]))

[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [0 1 2]]

### 문제 7 
x가 [0,0,0,1,2,3,0,2,1,0] 일때  앞 뒤의 0을 제거 하세요

In [88]:
x = np.array([0,0,0,1,2,3,0,2,1,0])
np.trim_zeros(x)

array([1, 2, 3, 0, 2, 1])